### PR TITLE
Documentation for the API

### PR DESCRIPTION
**Pull request by Nequil**
I have added to the README some simple documentation. Hopefully this will be helpful for new comers.

### CODE REVIEW

**Comment by Nequil** [comment]
Added Documentation and sending upstream

**Comment by Ethan-Vann** [comment]
denied. low quality/incorrect information

**Comment by Magnusrn** [comment]
> denied. low quality/incorrect information

Better than the garbage you've got Mr Ethan Vonn

**Comment by xl3ehindTon** [comment]
Real

**Pull request closed without merging**
